# Generated by Django 4.1.6 on 2023-12-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nik', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='current_user',
        ),
    ]
