# Generated by Django 4.1.6 on 2023-12-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nik', '0004_rename_current_user_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='current_user',
        ),
    ]
