# Generated by Django 4.1.6 on 2023-12-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nik', '0005_rename_user_profile_current_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='current_user',
            new_name='user',
        ),
    ]
