# Generated by Django 4.1.6 on 2023-12-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nik', '0007_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
